# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{epp-client}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Geoff Garside"]
  s.date = %q{2010-12-20}
  s.description = %q{Client for communicating with EPP services}
  s.email = %q{geoff@geoffgarside.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "epp-client.gemspec",
    "lib/epp-client.rb",
    "lib/epp-client/client.rb",
    "lib/epp-client/hello_request.rb",
    "lib/epp-client/old_server.rb",
    "lib/epp-client/request.rb",
    "lib/epp-client/response.rb",
    "lib/epp-client/response_error.rb",
    "lib/epp-client/server.rb",
    "test/helper.rb",
    "test/test_epp-client.rb"
  ]
  s.homepage = %q{http://github.com/geoffgarside/epp-client}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{EPP (Extensible Provisioning Protocol) Client}
  s.test_files = [
    "test/helper.rb",
    "test/test_epp-client.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<libxml-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<libxml-ruby>, [">= 0"])
  end
end

